spring.application.name=digcompsys

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/digcompsys_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=Harini
spring.datasource.password=Harini@987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=your_jwt_secret_key_123456789