spring.application.name=digcompsys

spring.datasource.url=jdbc:mysql://localhost:3306/digital_complaint_system
spring.datasource.username=Harini
spring.datasource.password=Harini@987

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


